FROM node:20
RUN apt-get update && apt-get install -y python3 ffmpeg && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY package.json yarn.lock ./
COPY ./prisma ./prisma
RUN yarn install --frozen-lockfile --ignore-engines
COPY ./tsconfig.json ./tsconfig.json
COPY ./sources ./sources
ENV NODE_ENV=production
EXPOSE 3005
CMD ["yarn", "start"]